# Site Config

name: AlexFlipnote
title: AlexFlipnote
twitter: AlexFlipnote

themecolour: "#2196F3"

domain: "https://alexflipnote.xyz"
baseurl: ""
url: "https://alexflipnote.xyz"
encoding: utf-8

include: ['_pages', '_docs']

markdown: kramdown

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  show_warnings:  false

sass:
  sass_dir: _sass
  style: compressed
